### PR TITLE
Add wrappers for Linux kernel header files

### PR DESCRIPTION
**Pull request by gruzdev**
This patch cleans up the code and fixes Linux kernel module build. Build error was mentioned in https://answers.launchpad.net/rohc/+question/399335 .

### CODE REVIEW

**Comment by didier-barvaux** [comment]
(sorry for the delay before review, I was in holidays)

Seems great! I will test it later this day before applying it.

**Comment by didier-barvaux** [comment]
I tested your patch. It works fine. I however found some more header to cleanup. I imported your branch and patched it further. It works fine for me. Could you please give it a try?

See https://github.com/didier-barvaux/rohc/commit/09456df5a1a4504ff604e34be0b1c057bf18b8df

**Comment by gruzdev** [comment]
I've checked it out. No build warnings. 'make check' passes with zero errors.
It turns out that kernel-level tests are broken. I'll look into it, no ETA though :) .

**Comment by didier-barvaux** [comment]
Thanks for the report. Kernel-level tests worked fine for me in June with several fixes ended by the merge https://github.com/didier-barvaux/rohc/commit/25ef2d4d91e96d565d3bb5b03aff35a1fac6f694 . Does 25ef2d4d91e96d565d3bb5b03aff35a1fac6f694 works for you? If yes the problem was introduced in between (may git bisect could help). If my fixes work for me but not for you :-/

**Comment by didier-barvaux** [comment]
Your branch doesn't merge cleanly any more. I updated mine to follow master: https://github.com/didier-barvaux/rohc/commits/stringh2

**Comment by didier-barvaux** [comment]
rebased on current master and merged as is, see https://github.com/didier-barvaux/rohc/commit/debcf10de5362bba8fb65d202911e7b11b81695a

**Pull request closed without merging**
