### PR TITLE
add function to create context with specific cid

### PR DESCRIPTION
**Pull request by MartinFretigne**
Hello Didier. In the program I'm working on I must be able to choose the context id used for a stream. I added a function rohc_comp_create_context to that end. Do you think you could merge such a feature in your repo ?

### CODE REVIEW

**Comment by didier-barvaux** [comment]
Hello,

Thank you for your patch. It looks interesting.

I would like to be sure to understand you use case. You would like to reserve some known context IDs for some streams. For example, let's reserve CID 0 for the stream with the most important volume. Or, more generally, use the smaller CIDs for the stream with the most important volume. Is it correct?

Would you also like that the reserved CIDs are never reused automatically even if there is no more traffic on them? Currently, the library uses a Least Recently Used (LRU) algorithm when it has to recycle a context. Your patch does not change that, so the context you reserved for one stream with very few packets might well be recycled, except if you call your new API function before compressing every packet of that stream.

I was thinking of a mechanism that would allow a program to reserve a given CID for a given stream. And, of course, to drop the reservation when it is not needed any more. In the meantime, the library won't recycle the reserved context by itself (the next Least Recently Used context will be recycled instead). The API may look like : 
* bool rohc_comp_reserve_context(struct rohc_comp *const comp, const rohc_cid_t cid, const struct rohc_buf uncomp_packet);
* bool rohc_comp_unreserve_context(struct rohc_comp *const comp, const rohc_cid_t cid);

Would such an API fulfill your use case?

Regards,
Didier Barvaux

**Comment by MartinFretigne** [comment]
I would like to reserve some CIDs for specifics streams, so that the CID used for a stream is known in advance. The CIDs and the corresponding stream used (identified by their IP address and port (source and destination)) are listed somewhere (outside of librohc), before the compression even begins.

In my program the reserved CIDs are only reused if it explicitly decide to (currently by calling rohc_comp_create_context), as there is a limited set of streams, each having its own CID defined outside of librohc.

Preventing the LRU algorithm from reusing the reserved CID will not be of any use for me, but see I see why would you like to do that, as it would be useful for a program that compress streams with reserved cids and streams without.

The API you propose would work very well for my use case. Thank you very much for your answer.
I will test it when it's implemented, when will you do that ?

Best Regards,
Martin Frétigné

**Comment by didier-barvaux** [comment]
OK, thank you for the confirmation.

You wrote "The CIDs and the corresponding stream used (identified by their IP address and port (source and destination)) are listed somewhere (outside of librohc), before the compression even begins". Do you get the IP addresses and TCP/UDP ports: 
1/ from network packets before ROHC compression?
2/ from another source unrelated with network packets (a configuration file maybe) ?

If your use case is 1/, then my API proposal seems perfect. However, if your use case is 2/, then the following API would allow you to reserve CIDs before receiving any network packet:
* bool rohc_comp_reserve_context(struct rohc_comp *const comp, const rohc_cid_t cid, const struct rohc_stream_attributes stream);
* bool rohc_comp_unreserve_context(struct rohc_comp *const comp, const rohc_cid_t cid);
with the following rohc_stream_attributes definition (example for one single IPv4 header) :
```
struct rohc_stream_attributes
{
    uint32_t ip_src_addr;
    uint32_t ip_dst_addr;
    uint8_t transport_protocol;
    uint16_t transport_src_port;
    uint16_t transport_dst_port;
};
```

What do you think of that API? Is it a better fit for your use case?

Regards,
Didier Barvaux

**Comment by MartinFretigne** [comment]
I'm in the case number 1 : I get the IP address and UDP ports from network packets. Your first proposal does indeed seem perfect, I like it more than the second one.

**Comment by didier-barvaux** [comment]
Martin,

OK. I'll work on this soon.

Regards,
Didier

**Comment by MartinFretigne** [comment]
Ok, thank you. I will keep an eye on that ticket and the master branch.

**Comment by didier-barvaux** [comment]
Replaced by https://github.com/didier-barvaux/rohc/pull/7

**Pull request closed without merging**
